### ISSUE TITLE
Shortcut for default beaviour

### ISSUE THREAD

**Issue by Nidre** [sblask/firefox-open-tabs-next-to-current#20]
Hello,

I'm the developer of a fork of your repository called "open tabs next to current plus". I've created that fork since I wanted "new tab button" to act with the default behavior. I see that option is now implemented in the original add-on.

I was wondering if you could add a keyboard shortcut to use default behavior too? If you could do that, I could simply remove my add-on and put a redirection link to yours since my version would no longer make sense to have. 

The feature I'm suggesting is, 

Ctrl + T would open a next to the current as it is right now.
Ctrl + Shift + Alt + T(for example, or maybe something configurable) would open the tab with default Firefox behavior, such as "new tab button"

If not I will try get my fork updated to comply with e10's, I honestly don't see any good reason except for that shortcut to have very similar add-ons.

Let me what do you think, I can help implementing the shortcut as well.

**Comment by Nidre** [comment]
I've just realized that Ctrl + Alt + T already does that? if that is the case, I would be happy to redirect my for and add-on to yours and stop the development of it.

Can you confirm Ctrl + Atl + T is intended to work with the default behavior? Can you possibly make it configurable through the settings to prevent any conflict with other add-ons?

**Comment by sblask** [comment]
Yes, `Ctrl+Alt+T` does it. I know there are conflicts with default Linux shortcuts and special characters accessible by `Alt Gr` and I was thinking about making it configurable for a long time. However, now with the add-on SDK having its end of life set to end of next year, I am not very motivated to do something about it. A migration to webextension is not currently possible due to lack of APIs (session recovery events and UI integration(button)). The UI integration is also what prevents me from making it e10s compatible now.

**Comment by Nidre** [comment]
Hmm alright then.  I will put the redirection active as soon as I can since the original add-on seems to have all the features that I've implemented in mine already implemented.

Thanks for the reply!

**Comment by Nidre** [comment]
@sblask 

As of now I've added the notice on the add-on page and the GitHub stating that open-tabs-next-to-current-plus will be discontinued and provided links to this add-on.

You can close this issue if you would like.
