### ISSUE TITLE
No longer appears to work in Firefox 53?

### ISSUE THREAD

**Issue by ElvinMo** [sblask/firefox-open-tabs-next-to-current#22]
Hi, thanks a lot for a great extension that has become essential to my life!

Recently, however, it has stopped working. I hypothesise that it's because of my system now updating to Firefox 53, but I'm not very sure.

I'm also not technical, but am happy to provide any settings etc. that help you track this down.

**Comment by sblask** [comment]
Hm, works fine for me, with 53 and 55 nightly, multiprocessing enabled. Maybe you've got some add-on installed that does something weird?

**Comment by ElvinMo** [comment]
Perhaps! I'll disable all my add-ons and see how we go. Will let you know.

________________________________

**Comment by Ganton** [comment]
The same happened to me just after updating to Firefox 53: Open Tabs Next To Current stopped working :-(

I tried disabling all the add-ons, but Open Tabs Next To Current no longer works.

**Comment by sblask** [comment]
I think it must be due to Mozilla's upgrade strategy related to multiprocessing - even though it still worked for me... I uploaded a beta version that is based on the webextension APi to https://addons.mozilla.org/en-GB/firefox/addon/open-tabs-next-to-current/ (Development Channel at the bottom) It doesn't have the shortcut for default behaviour implemented yet and I can no longer listen to session events (so a session restore might reverse the tab order) but the basic functionality should work. The setting `browser.tabs.insertRelatedAfterCurrent` from `about:config` is honoured, so you'll have to set it to false if you want tabs to be strictly opened to the right of the current tab.

**Comment by peteruithoven** [comment]
Could it be that that beta version also disables Electrolysis/Multiprocess? I notice that when after I enabled it and restarted Firefox `about:support` shows `Multiprocess Windows: 0/4 (Disabled by add-ons)`.

**Comment by VincentSC** [comment]
It never had support for multiprocess. For a reference see https://github.com/sblask/firefox-open-tabs-next-to-current/pull/21#event-1066471837

**Comment by sblask** [comment]
@peteruithoven yes, the add-on is still an embedded webextension. Not far off from being a full one, but I wanted to bring out a version that is not totally broken as quickly is possible. Stay tuned.

**Comment by peteruithoven** [comment]
@VincentSC I did see that comment, I guess I was naively assuming that by moving to WebExtensions that would automatically be supported. 

@sblask Thanks for clearing that up and putting in the work!

**Comment by sblask** [comment]
Just uploaded a new beta. Now a full webextension and `Ctrl-Y` implemented as shortcut to open a tab at the default location. You might run into this one though: https://bugzilla.mozilla.org/show_bug.cgi?id=1362147

**Comment by peteruithoven** [comment]
Awesome! `about:support` now indicates: `Multiprocess Windows: 5/5 (Enabled by default)`.

**Comment by r-a-y** [comment]
FWIW, the addon is working fine for me in FF 53.

**Comment by sblask** [comment]
The new version just went through review and is now available.
