### ISSUE TITLE
WebExtension - New tab moves to the beginning of the visible tab bar

### ISSUE THREAD

**Issue by r-a-y** [sblask/firefox-open-tabs-next-to-current#24]
I'm testing the new beta and opening a new tab has the effect of moving the tab bar to the first position of the new tab.

For example, let's say tab 12 is the active tab:

| tab 10 | tab 11 | tab 12 (active) | tab 13 | tab 14... 30 |

If I open a new tab, then the tab bar becomes:

| tab 13 (new tab) | tab 14 | tab 15 | tab 16 | tab 17... 30 |

I much prefer the older XUL method of the tabbar not moving:

| tab 10 | tab 11 | tab 12 | tab 13 (new tab) | tab 14 | tab 15... 30 |

This is probably a limitation of the new WebExtension API, but thought I'd post an issue about this.

**Comment by sblask** [comment]
There is and was nothing that I actively do about the positioning of the tabbar. I only move the tab once it's opened. I assume the webextension API kicks in a little later so the tab is actually opened at the end, so the tabbar is moved to the end and when I move the tab, it's scrolled back enough so the tab stays visible. The only thing I could do is moving it before tab 10 in your example and then move it to the final place, but it would be more guesswork than anything else, there is nothing to control the tabbar position directly. BTW, I don't have this problem because I set up my tabs so they are always visible and shrink like they do in Chrome. Having not all my tabs visible would be very annoying for me...

**Comment by r-a-y** [comment]
>  BTW, I don't have this problem because I set up my tabs so they are always visible and shrink like they do in Chrome. Having not all my tabs visible would be very annoying for me...

This wouldn't work for me since I have ~100 tabs in my current window :sweat_smile: 

I think I might have to stick with Firefox 56 just so I can keep using the XUL version of your addon.

**Comment by sblask** [comment]
The new version just went through review, if you want to keep the old one, you'll have to disable automatic updates.

**Comment by NabiKAZ** [comment]
I have this problem exactly, when I have many tabs.
Open Tabs Next to Current 2.0.2
Firefox 53.0.2 (64-bit)

I don't have this problem with [tab-deque](https://addons.mozilla.org/en-US/firefox/addon/tab-deque/) v1.1.5
