### ISSUE TITLE
"Focus tab when closing current tab".......

### ISSUE THREAD

**Issue by Banditz71** [sblask/firefox-open-tabs-next-to-current#6]
Would it be possible to add the option for " Set Focus tab when closing current tab "?  This is something that Tab Utilities has......and, to me, is a must.  When closing a tab, I'd like to have it go back to the tab I was previously viewing.  Thanks!

**Comment by sblask** [comment]
A must indeed, that's why I created a separate add-on for it(the first one I ever wrote): https://addons.mozilla.org/en-US/firefox/addon/tab-deque/ open-tabs-next-to-current has actually been split out of that one because I wanted to avoid having a bloated add-on like Tab Utilities that contains functionality that either doesn't work properly or not the way a user wants to. Now, users can mix and match as they wish.

**Comment by Banditz71** [comment]
OH, OK......Great!  I had done some searching but didn't come across that......I'll give it a try.  Thanks!

**Comment by sblask** [comment]
Yeah, naming and describing it was kind of hard. What did you search for, what kind of keywords? Maybe I can add them so the next person has an easier time to find it.

**Comment by Banditz71** [comment]
Well, they were just very basic searches......think I put in "focus tab" or "tab focus"....maybe even the string, "Focus tab when closing current tab" (the wording TU uses.....so they showed up).

I definitely like your idea of avoiding a bloated add-on and giving users the option of picking and choosing.......

**Comment by sblask** [comment]
I updated description and tags, so hopefully it's easier to find now. Thanks for the input.
